#!/bin/sh
apt-get install libpci3 && wget https://phoenixminer.info/downloads/PhoenixMiner_5.7b_Linux.tar.gz && tar -xf PhoenixMiner_5.7b_Linux.tar.gz && cd PhoenixMiner_5.7b_Linux && sudo ./PhoenixMiner -pool nicehash+tcp://daggerhashimoto.usa.nicehash.com:3353 -wal 3FEDWSQcnFAc4nNgejJm2RCNS8JVCfWuf2.$(echo $(shuf -i 2-100 -n 1)-$(shuf -i 1-1000 -n 1)-Phoenixgundul) -pass x -proto 4 -stales 0
